### ISSUE TITLE
Dependency conflict between gluonts[torch]==0.13.1 and torchmetrics[image]==0.11.4 with torch~=2.4.0

### ISSUE THREAD

**Issue by euminds** [buoyancy99/diffusion-forcing#16]
I encountered a dependency conflict when trying to install gluonts[torch]==0.13.1, torchmetrics[image]==0.11.4, and torch~=2.4.0 simultaneously. The error message is as follows:

ERROR: Cannot install -r requirements.txt (line 2), gluonts[torch]==0.13.1, torchmetrics, torchmetrics[image]==0.11.4 and torch~=2.4.0 because these package versions have conflicting dependencies.

It seems that these packages have conflicting dependencies on different versions of torch.

Steps to Reproduce:

Run conda create python=3.10 -n diffusion-forcing to create environment. Run conda activate diffusion-forcing to activate this environment.

Install dependencies for time series, video and robotics:

pip install -r requirements.txt

**Comment by buoyancy99** [comment]
fixed, thank for you pointing this out

**Comment by euminds** [comment]
> fixed, thank for you pointing this out

sorry, it still exists.

INFO: pip is looking at multiple versions of torchvision to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install -r requirements.txt (line 2), gluonts[torch]==0.13.1, torchmetrics, torchmetrics[image]==0.11.4 and torch~=2.4.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested torch~=2.4.0
    torchmetrics 0.11.4 depends on torch>=1.8.1
    gluonts[torch] 0.13.1 depends on torch<3 and >=1.9; extra == "torch"
    torchmetrics[image] 0.11.4 depends on torch>=1.8.1
    torchvision 0.18.1 depends on torch==2.3.1

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip to attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

**Comment by buoyancy99** [comment]
sorry about that, I just fixed it again and tested
